name: manual_camera_example
description: Demonstrates how to use the camera plugin.

dependencies:
  manual_camera:
    path: ../
  path_provider: ^2.0.13
  flutter:
    sdk: flutter
  video_player: ^2.6.0
  camera: ^0.10.3+2 #^0.9.1+1 #^0.10.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  lints: ^2.0.1

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.4 <2.0.0"
